### PR TITLE
convert bytes to string before json parsing for python 3 support - cl…

### PR DESCRIPTION
**Pull request by duhaime**
…oses #111

### CODE REVIEW

**Comment by duhaime** [comment]
it looks like this one method handles all json parsing for the app (nice factoring!), so this should take care of python 3 users...

**Comment by mtrovo** [comment]
Hey, thanks for the PR, I think it's better to solve this problem by using `resp.json()` from `requests` directly. Would you mind updating your PR to handle it this way?

**Comment by duhaime** [comment]
@mtrovo sounds good! 

I also added a test for bytes responses, and took a moment to update some method calls in the extant tests that were throwing deprecated method warnings.

**Comment by duhaime** [comment]
@mtrovo just checking in to see if you saw these changes!

**Comment by duhaime** [comment]
ping @mtrovo

**Comment by duhaime** [comment]
I just pinged both of you as the library blows up in Python 3 without this change, and Python 2 is now largely defunct...

**Comment by duhaime** [comment]
@alexis-mignon Merci!

**Pull request merged**
